### ISSUE TITLE
Moving realtime-tool to realtime.realworldvisuals.com has broken something

### ISSUE THREAD

**Issue by adamnieman** [martha-anne/realtime-tool#1]
The form that allows users to enter the rate of emissions is missing. I think originally the form was on the left hand side of the page. Now we just get an alert (see attached screenshot).

![screenshot 2017-10-16 12 31 40](https://user-images.githubusercontent.com/1668515/31609931-006259a8-b26e-11e7-82ae-7eed49418b2c.png)

**Comment by martinjoiner** [comment]
That was realtime-vis-ctx that had the form.  What does "CTX" stand for though?

**Comment by adamnieman** [comment]
I can't remember what CTX means. Do you know what happened to realtime-vis-ctx?

**Comment by martinjoiner** [comment]
I have put the "CTX" version live again at http://realtime-ctx.realworldvisuals.com/ but I do recommend we rename it to something other than an acronym that will be forgotten.  Is it possible it's a short form of "Context"?

**Comment by adamnieman** [comment]
Thank you
